language: ruby
before_install:
- gem install bundler
rvm:
- 2.1.0
deploy:
  provider: heroku
  app: lukeburroughs
  on:
    repo: falconx/luke
  api_key:
    secure: Bmu2VFud2kGghkJcF3nre8E7WiIVVjnKp/12+VwRcMQriswJOxlwJWG4gvP616QlzMRc3gczX0etFOzywnG91BO4Ufmlqu5GpbabKxm6lbmlNv7Qvf8jeHVRB1+THqA/fQRu+MBNDyK0HJTEmXA4SbLWng01mfgLavvCkISGGNY=
