deploy:
  provider: heroku
  api_key:
    secure: Rdwxwgg7oCd0hYVDL7ZBy4VbbGpexXGNZ334dXHYUDSops07C26xL4WnrS+bsLx5W6WxNU8hj0WjuZTIXUI+oy1C51v3K5bzZ2uk1roq3T+ikwhwkjbfSmVJ69XB8SI3NIWL/4XfkF4s7nnvTDzDZBoDcHlyK7lY9rhEb77cVpI=
  app: lukeburroughs
  on:
    repo: falconx/luke
language: ruby
before_deploy: echo '--- before deploy ---'
after_deploy: echo '--- after deploy ---'
script: bundle exec jekyll build
