language: ruby

before_install:
  - gem install bundler

rvm:
  - 2.1.0

deploy:
  provider: heroku
  api_key:
    secure: pfQSXgn8o7aUnpGgJg7Wf2M+9+bNcQ9kFpAwk6+iFHhmJGUY6XBP2RPoSAHTyKk0EVHL5NwcOqFXEWcr0ejaZrzYnShAvhjcXp0QjorG3t07ov2LLBwCPnDHLrUHNzmoYGnzhSRPDE17LeEJnfRTM0X55NfhPY4T3ZjMKb51BsI=
  app: lukeburroughs
  on:
    repo: falconx/lukeburroughs
