deploy:
  provider: heroku
  api_key:
    secure: pfQSXgn8o7aUnpGgJg7Wf2M+9+bNcQ9kFpAwk6+iFHhmJGUY6XBP2RPoSAHTyKk0EVHL5NwcOqFXEWcr0ejaZrzYnShAvhjcXp0QjorG3t07ov2LLBwCPnDHLrUHNzmoYGnzhSRPDE17LeEJnfRTM0X55NfhPY4T3ZjMKb51BsI=
  app: lukeburroughs
  on:
    repo: falconx/luke

language: ruby
#script: bundle exec jekyll build
#install: bundle install

before_deploy: "echo '--- before deploy ---'"
after_deploy: "echo '--- after deploy ---'"
script: "bundle exec jekyll build"
