name: Luke Burroughs Portfolio
pygments: true

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
